
services:
  backend:
    image: devendern/django-backend:latest   # ✅ FROM DOCKER HUB
    container_name: django-backend
    ports:
      - "8010:8000"
    networks:
      - edtech-network

  frontend:
    image: devendern/react-frontend:latest   # ✅ FROM DOCKER HUB
    container_name: react-frontend
    ports:
      - "3010:80"
    networks:
      - edtech-network
    depends_on:
      - backend

networks:
  edtech-network:
    driver: bridge

